QuestionBaseSystem/urls.py
from django.contrib import admin
from django.urls import path, include
import Consumer.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Consumer.views.login, name='Consumer.views.login'),#进入服务器直接进入用户登录界面
    path('user/', include('Consumer.urls')),
    path('index/', include('index.urls')),
    path('exam/', include('exam.urls')),
    path('collectTestpaper/',include('CollectTestpaper.urls')),

]

exam/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.exam),
]

CollectTestpaper/models.py
from django.db import models

# Create your models here.
'''试卷'''
class Testpaper(models.Model):
    testpaper_id = models.BigAutoField(primary_key=True,verbose_name="试卷id")
    name = models.CharField(max_length=50, blank=True, null=True,verbose_name="试卷名")
    #试卷简介text
    intro = models.TextField(blank=True, null=True, verbose_name="试卷简介")
    #出题时间date
    apply_time = models.DateField(blank=True, null=True, verbose_name="出题时间")
    #试卷难度char
    hard_choices = (
        (0, "简单"),
        (1, "中等"),
        (2, "较难"),
        (3, "难"),
        (4, "很难"),
    )
    hard = models.IntegerField(blank=True, null=True, choices=hard_choices, verbose_name="试卷难度")
    class Meta:
        verbose_name = '试卷'
        verbose_name_plural = '试卷'
#models.ForeignKey(to="",to_field ="",on_delete=models.CASCADE)
'''外键约束模型'''

'''试卷_试题'''
class TestpaperQuestion(models.Model):
    testpaper_id = models.ForeignKey(to="Testpaper", to_field="testpaper_id", on_delete=models.CASCADE, verbose_name="试卷id")
    question_id = models.ForeignKey(to="Question", to_field="question_id", on_delete=models.CASCADE, verbose_name="试题id")
    class Meta:
        verbose_name = '试卷_试题'
        verbose_name_plural = '试卷_试题'

'''试题'''
class Question(models.Model):
    question_id = models.BigAutoField(primary_key=True, verbose_name="试题id")
    stems = models.TextField(blank=True, null=True, verbose_name="题干")
    level_choices=(
        (1, "选择题"),
        (2, "判断题"),
        (3, "填空题"),
    )
    level = models.IntegerField(verbose_name="试题类型",choices=level_choices,blank=True, null=True)
    class Meta:
        verbose_name = '试题'
        verbose_name_plural = '试题'

'''选择题'''
class Choice(models.Model):
    question_id = models.ForeignKey(to="Question", to_field="question_id", on_delete=models.CASCADE, verbose_name="试题id")
    # stems = models.TextField(blank=True, null=True, verbose_name="题干")
    choice1 = models.CharField(max_length=80, blank=True, null=True,verbose_name="选项A")
    choice2 = models.CharField(max_length=80, blank=True, null=True,verbose_name="选项B")
    choice3 = models.CharField(max_length=80, blank=True, null=True,verbose_name="选项C")
    choice4 = models.CharField(max_length=80, blank=True, null=True,verbose_name="选项D")
    standard_answer = models.CharField(max_length=255, blank=True, null=True,verbose_name="标准答案")
    score = models.IntegerField(default=2, verbose_name="分值")
    class Meta:
        verbose_name = '选择题'
        verbose_name_plural = '选择题'
    def dis_Question(self):
        return self.question_id.stems
    dis_Question.short_description = "题干"

'''填空题'''
class Gapfill(models.Model):
    question_id = models.ForeignKey(to="Question", to_field="question_id", on_delete=models.CASCADE, verbose_name="试题id")
    # stems = models.TextField(blank=True, null=True, verbose_name="题干")
    standard_answer = models.CharField(max_length=255, blank=True, null=True,verbose_name="标准答案")
    score = models.IntegerField(default=3, verbose_name="分值")
    class Meta:
        verbose_name = '填空题'
        verbose_name_plural = '填空题'
    def dis_Question(self):
        return self.question_id.stems
    dis_Question.short_description = "题干"

'''判断题'''
class TrueOrFalse(models.Model):
    question_id = models.ForeignKey(to="Question", to_field="question_id", on_delete=models.CASCADE, verbose_name="试题id")
    # stems = models.TextField(blank=True, null=True, verbose_name="题干")
    standard_answer = models.CharField(max_length=255, blank=True, null=True,verbose_name="标准答案")
    score = models.IntegerField(default=1, verbose_name="分值")
    class Meta:
        verbose_name = '判断题'
        verbose_name_plural = '判断题'
    def dis_Question(self):
        return self.question_id.stems
    dis_Question.short_description = "题干"

index/templates/PersonalCenter.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>我的题库中心-模拟考试</title>
    <link rel="stylesheet" href="/../static/CSS/PersonalCenter.css">
</head>
<body>
    <div class="banner">
        <a href="/index/"><h>试题管理系统</h></a>
        <div class="status">
            <ul>
                <li><a href="/user/login/"><h>切换账号</h></a></li>
                <li><a href="/index/personalCenter/"><h>我的题库中心</h></a></li>
                <li><a href="/user/{{ useraccount }}/modify/"><h>个人中心</h></a></li>
                <li><a href="#"><h>我的博客</h></a></li>
            </ul>
        </div>
    </div>
    <div class="center_left">
        <img class="new_pk01" src="/../static/img/newpk01.png" alt="">
        <div class="new_pk02"><img src="/../static/img/newpk02.png" alt=""></div>
    </div>

    <div class="center_right">
        <div class="right_context">
            <a class="bt_p" href="/index/personalCenter/">模拟考试</a>
            <a class="bt_p" href="/index/personalCenter2/">我的题目集</a>
        </div>
        <ul>
            {% for i in TestData.items %}
                <li class="right_context right_li">
                    <a href="/exam/?TestpaperID={{ i.0 }}">{{ i.1}}</a>
                    <a style="float:right; margin-right: 30px; font-size: 25px;" href="/index/personalCenter/delete/?TestpaperID={{ i.0 }}">删除</a>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div class="center_left_text">建议反馈：1348757279@qq.com</div>
</body>
</html>

index/templates/PersonalCenter2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>我的题库中心-题目集</title>
    <link rel="stylesheet" href="/../static/CSS/PersonalCenter.css">
</head>
<body>
    <div class="banner">
        <a href="/index/"><h>试题管理系统</h></a>
        <div class="status">
            <ul>
                <li><a href="/user/login/"><h>切换账号</h></a></li>
                <li><a href="/index/personalCenter/"><h>我的题库中心</h></a></li>
                <li><a href="/user/{{ useraccount }}/modify/"><h>个人中心</h></a></li>
                <li><a href="#"><h>我的博客</h></a></li>
            </ul>
        </div>
    </div>
    <div class="center_left">
        <img class="new_pk01" src="/../static/img/newpk01.png" alt="">
        <div class="new_pk02"><img src="/../static/img/newpk02.png" alt=""></div>
    </div>

    <div class="center_right">
        <div class="right_context">
            <a class="bt_p" href="/index/personalCenter/">模拟考试</a>
            <a class="bt_p" href="/index/personalCenter2/">我的题目集</a>
        </div>
        <ul>
            <li class="right_context right_li">
                <a class="" href="#">数据库模拟题库1</a>
                <p>分</p><p>100</p><p>分数:</p>
            </li>
            <li class="right_context right_li">
                <a class="" href="#">Java模拟题库1</a>
                <p>分</p><p>100</p><p>分数:</p>
            </li>
            <li class="right_context right_li">
                <a class="" href="#">数据库模拟题库1</a>
                <p>分</p><p>100</p><p>分数:</p>
            </li>
            <li class="right_context right_li">
                <a class="" href="#">Java模拟题库1</a>
                <p>分</p><p>100</p><p>分数:</p>
            </li>
            <li class="right_context right_li">
                <a class="" href="#">数据库模拟题库1</a>
                <p>分</p><p>100</p><p>分数:</p>
            </li>
            <li class="right_context right_li">
                <a class="" href="#">Java模拟题库1</a>
                <p>分</p><p>100</p><p>分数:</p>
            </li>
            <li class="right_context right_li">
                <a class="" href="#">数据库模拟题库1</a>
                <p>分</p><p>100</p><p>分数:</p>
            </li>
            <li class="right_context right_li">
                <a class="" href="#">Java模拟题库1</a>
                <p>分</p><p>100</p><p>分数:</p>
            </li>
            <li class="right_context right_li">
                <a class="" href="#">数据库模拟题库1</a>
                <p>分</p><p>100</p><p>分数:</p>
            </li>
            <li class="right_context right_li">
                <a class="" href="#">Java模拟题库1</a>
                <p>分</p><p>100</p><p>分数:</p>
            </li>
            <li class="right_context right_li">
                <a class="" href="#">数据库模拟题库1</a>
                <p>分</p><p>100</p><p>分数:</p>
            </li>
            <li class="right_context right_li">
                <a class="" href="#">Java模拟题库1</a>
                <p>分</p><p>100</p><p>分数:</p>
            </li>
        </ul>
    </div>
    <div class="center_left_text">建议反馈：1348757279@qq.com</div>
</body>
</html>

index/templates/educater_supermarket.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>教育超市</title>
    <link rel="stylesheet" href="/../static/CSS/index.css">
    <link rel="stylesheet" href="/../static/CSS/bootstrap.min.css">
    <style>
        .center {
            width: 600px;
            margin: 80px auto;
            text-align: center;
            font-weight: bold;
            padding-bottom: 10px;
            border-bottom: #6d6d6d 1px solid;
            font-size: 56px;
        }

        .center1 {
            width: 600px;
            margin: 10px auto;
            text-align: center;
            font-weight: bold;
            padding-bottom: 10px;
            border-bottom: #6d6d6d 1px solid;
            font-size: 56px;
        }

        .column {
            display: flex;
            margin-bottom: 30px;
        }

        .left {
            flex: 1;
            margin: 0 auto;
            text-align: center;
            font-size: 36px;
        }

        .right {
            flex: 1;
            margin: 0 auto;
            text-align: center;
            font-size: 36px;

        }

        .num {
            color: rgb(25, 214, 172);
            font-weight: bold;


        }
        a{
            color: black;
        }
        a:hover{
            text-decoration: none;
        }
    </style>
</head>
<body>
<div class="banner">
    <a href="/index/">
        <h>试题管理系统</h>
    </a>
    <div class="status">
        <ul>
            <li><a href="/user/login/">
                <h>切换账号</h>
            </a></li>
            <li><a href="/index/personalCenter/">
                <h>我的题库中心</h>
            </a></li>
            <li><a href="/user/{{ useraccount }}/modify/">
                <h>个人中心</h>
            </a></li>
            <li><a href="#">
                <h>我的博客</h>
            </a></li>
        </ul>
    </div>
</div>
<div class=" container-fluid">
    <h1 class="center">以有价之物兑无价之宝</h1>

    <div class="row column">
        <div class="left" style="padding-top: 40px">
            <p class="center1" style="border: none">最新上架</p>
            {% for item in rank_time_text %}
                <div class="column">
                    <div class="left num">- 0{{ forloop.counter }} -</div>

                    <div class="right" style="flex: 2;text-align: left"><a href="/index/test/?id={{ item.testpaper_id }}">{{ item.name }}</a></div>
                </div>
            {% endfor %}
        </div>
        <div class="right">
            <p class="center1" style="border: none">热门排行</p>
            {% for v in rank_hot_lis %}


                <div class="column">
                    <div class="left num">- 0{{ forloop.counter }} -</div>
                    {% for k,y in v.items %}

                        <div class="right" style="flex: 2;text-align: left"><a href="/index/test/?id={{ y.testpaper_id }}">{{ y.name }}</a></div>
                    {% endfor %}
                </div>
            {% endfor %}
        </div>

    </div>
</div>

<hr>
<div class="" style="width: 1900px; background-color: #ffffff">
    {% for item in all %}
        <div style="display: inline-block;width: 600px;margin-left: 17px;margin-top: 10px;text-align: center;">
            <a href="/index/test/?id={{ item.testpaper_id }}">
                <p style="margin-left: 50%;" class="left">
                    {{ item.name }}
                </p></a>
        </div>
    {% endfor %}

</div>

<div class="footer">
    <div class="author">
        <ul>
            <li>
                <span class="text_footer1">@author</span>
                <span class="text_footer2">&ensp;@number</span>
            </li>
            <li>
                <span class="text_footer1">范斌</span>
                <span class="text_footer2">&ensp;&ensp;18647377201</span>
            </li>
            <li>
                <span class="text_footer1">梁琛宙</span>
                <span class="text_footer2">13394893813</span>
            </li>
            <li>
                <span class="text_footer1">章宇翔</span>
                <span class="text_footer2">18355184261</span>
            </li>
            <li>
                <span class="text_footer1">石帅龙</span>
                <span class="text_footer2">18947787100</span>
            </li>
        </ul>
    </div>
</div>


</body>
</html>

index/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
    <link rel="stylesheet" href="/../static/CSS/index.css">
</head>
<body>
    <div class="banner">
        <a href="/index/"><h>试题管理系统</h></a>
        <div class="status">
            <ul>
                <li><a href="/user/login/"><h>切换账号</h></a></li>
                <li><a href="/index/personalCenter/"><h>我的题库中心</h></a></li>
                <li><a href="/user/{{ useraccount }}/modify/"><h>个人中心</h></a></li>
                <li><a href="#"><h>我的博客</h></a></li>
            </ul>
        </div>
    </div>
    <div class="center_body">
        <div class="title_head">
            <a href="/index/subjectDesc/">学科</a>
            <a href="#">学科</a>
            <a href="#">学科</a>
            <a href="#">学科</a>
            <a href="#">学科</a>
            <a href="#">学科</a>
        </div>
        <div class="major_center">
            <div class="education_supermarket">
                <a class="education_text" href="/index/educater_supermarket/">教育超市</a>
                <hr class="hr_education">
                <ul>
                    {% for item in rank_four %}
                    <li>
                        <a class="inner_education" href="/index/test?id={{ item.testpaper_id }}">
                            <span class="inner_text1">{{ item.name }}</span>
                            <span class="inner_text2">入门算法必刷练习题库</span>
                        </a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="center_right">
            <span class="inner_text1">刷题排行榜</span>
            <ul>
                <li>
                    <a href="#"><span>1.用户xxxxx</span></a>
                </li>
                <li>
                    <a href="#"><span>2.用户xxxxx</span></a>
                </li>
                <li>
                    <a href="#"><span>3.用户xxxxx</span></a>
                </li>
                <li>
                    <a href="#"><span>4.用户xxxxx</span></a>
                </li>
                <li>
                    <a href="#"><span>5.用户xxxxx</span></a>
                </li>
                <li>
                    <a href="#"><span>6.用户xxxxx</span></a>
                </li><li>
                    <a href="#"><span>7.用户xxxxx</span></a>
                </li>
                <li>
                    <a href="#"><span>8.用户xxxxx</span></a>
                </li>
                <li>
                    <a href="#"><span>9.用户xxxxx</span></a>
                </li>
                <li>
                    <a href="#"><span>10.用户xxxxx</span></a>
                </li>
                <span class="center_right_text">您的排名</span><span class="center_right_text">100+</span>
            </ul>
        </div>
        <div class="demo_line"></div>
        <div class="education_supermarket">
             <a class="education_text2" href="#">学科视频推荐</a>
                <hr class="hr_education">
                <ul>
                    <li>
                        <a class="inner_education" href="#">
                            <span class="inner_text1">算法入门训练</span>
                            <span class="inner_text2">入门算法必刷练习题库</span>
                        </a>
                    </li>
                    <li>
                        <a class="inner_education" href="#">
                            <span class="inner_text1">算法入门训练</span>
                            <span class="inner_text2">入门算法必刷练习题库</span>
                        </a>
                    </li>
                    <li>
                        <a class="inner_education" href="#">
                            <span class="inner_text1">算法入门训练</span>
                            <span class="inner_text2">入门算法必刷练习题库</span>
                        </a>
                    </li>
                    <li>
                        <a class="inner_education" href="#">
                            <span class="inner_text1">算法入门训练</span>
                            <span class="inner_text2">入门算法必刷练习题库</span>
                        </a>
                    </li>
                </ul>
        </div>
    </div>
    <div class="footer">
        <div class="author">
            <ul>
                <li>
                    <span class="text_footer1">@author</span>
                    <span class="text_footer2">&ensp;@number</span>
                </li>
                <li>
                    <span class="text_footer1">范斌</span>
                    <span class="text_footer2">&ensp;&ensp;18647377201</span>
                </li>
                <li>
                    <span class="text_footer1">梁琛宙</span>
                    <span class="text_footer2">13394893813</span>
                </li>
                <li>
                    <span class="text_footer1">章宇翔</span>
                    <span class="text_footer2">18355184261</span>
                </li>
                <li>
                    <span class="text_footer1">石帅龙</span>
                    <span class="text_footer2">18947787100</span>
                </li>
            </ul>
        </div>
    </div>


</body>
</html>

index/templates/subjectDesc.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>学科题库</title>
    <link rel="stylesheet" href="/../static/CSS/subjectDesc.css">
</head>
<body>
    <div class="banner">
        <a href="/index/"><h>试题管理系统</h></a>
        <div class="status">
            <ul>
                <li><a href="/user/login/"><h>切换账号</h></a></li>
                <li><a href="/index/personalCenter/"><h>我的题库中心</h></a></li>
                <li><a href="/user/{{ useraccount }}/modify/"><h>个人中心</h></a></li>
                <li><a href="#"><h>我的博客</h></a></li>
            </ul>
        </div>
    </div>
    <div class="center_body">
        <div class="title_head">
            <a href="/index/subjectDesc/">学科</a>
            <a href="#">学科</a>
            <a href="#">学科</a>
            <a href="#">学科</a>
            <a href="#">学科</a>
            <a href="#">学科</a>
        </div>
        <div class="title_first"><h>学科</h></div>
        <dl>
            <div class="inner_context">
                <dt>2020年备考</dt>
                <dd><a href="#">2020数据库期中一</a></dd>
                <dd><a href="#">2020数据库期中一</a></dd>
                <dd><a href="#">2020数据库期中一</a></dd>
                <dd><a href="#">2020数据库期中一</a></dd>
            </div>
            <div class="inner_context">
                <dt>2021年备考</dt>
                <dd><a href="#">2020数据库期中一</a></dd>
                <dd><a href="#">2020数据库期中一</a></dd>
                <dd><a href="#">2020数据库期中一</a></dd>
                <dd><a href="#">2020数据库期中一</a></dd>
                <dd><a href="#">2020数据库期中一</a></dd>
            </div>
            <div class="inner_context">
                <dt>2022年备考</dt>
                <dd><a href="#">2020数据库期中一</a></dd>
                <dd><a href="#">2020数据库期中一</a></dd>
                <dd><a href="#">2020数据库期中一</a></dd>
                <dd><a href="#">2020数据库期中一</a></dd>
                <dd><a href="#">2020数据库期中一</a></dd>
            </div>
            <div class="inner_context">
                <dt>2022年备考</dt>
                <dd><a href="#">2020数据库期中一</a></dd>
                <dd><a href="#">2020数据库期中一</a></dd>
                <dd><a href="#">2020数据库期中一</a></dd>
                <dd><a href="#">2020数据库期中一</a></dd>
                <dd><a href="#">2020数据库期中一</a></dd>
            </div>
        </dl>
    </div>
</body>
</html>

index/templates/text.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>测试</title>
    <link rel="stylesheet" href="/../static/CSS/index.css">
    <link rel="stylesheet" href="/../static/CSS/bootstrap.min.css">
    <style>
        .text_body {
            display: flex;
        }

        .left {
            flex: 1;
        }

        .right {
            flex: 3;
        }
        .text{
            margin: 10px ;
            font-size: 20px;
        }
    </style>
</head>
<body>
<div class="banner">
    <a href="/index/">
        <h>试题管理系统</h>
    </a>
    <div class="status">
        <ul>
            <li><a href="/user/login/">
                <h>切换账号</h>
            </a></li>
            <li><a href="/index/personalCenter/">
                <h>我的题库中心</h>
            </a></li>
            <li><a href="/user/{{ useraccount }}/modify/">
                <h>个人中心</h>
            </a></li>
            <li><a href="#">
                <h>我的博客</h>
            </a></li>
        </ul>
    </div>
</div>

<div class="container">
    <h1 style="text-align: center">{{ test.name }}</h1>
    <div class="text_body">
        <div class="left">
            <div><img src="../../static/img/img.png" alt="" width="120px" height="144px"></div>
            <p class="text" style="margin-left: 0">题目难度：{{ test.get_hard_display }}</p>
        </div>
        <div class="right">
            <div class="text">试卷简介：</div>
            <div class="text" style="width: 600px; margin-left: 30px;">{{ test.intro }}</div>

            <div  class="text">出题时间：{{ test.apply_time }}</div>
            <div  class="text">已被订阅人数：{{ count }}  </div>

            {% if status == 0 %}
                <a href="/index/add?id={{ test.testpaper_id }}"><div class="btn btn-info"> 添加入到我的题库</div></a>
                {% else %}
                <a href="/index/delete?id={{ test.testpaper_id }}"><div class="btn btn-info"> 删除题库</div></a>
            {% endif %}
        </div>
    </div>
</div>


<div class="footer">
    <div class="author">
        <ul>
            <li>
                <span class="text_footer1">@author</span>
                <span class="text_footer2">&ensp;@number</span>
            </li>
            <li>
                <span class="text_footer1">范斌</span>
                <span class="text_footer2">&ensp;&ensp;18647377201</span>
            </li>
            <li>
                <span class="text_footer1">梁琛宙</span>
                <span class="text_footer2">13394893813</span>
            </li>
            <li>
                <span class="text_footer1">章宇翔</span>
                <span class="text_footer2">18355184261</span>
            </li>
            <li>
                <span class="text_footer1">石帅龙</span>
                <span class="text_footer2">18947787100</span>
            </li>
        </ul>
    </div>
</div>


</body>
</html>